(()=>{
const SUPA='https://nqqctoqyvkdgdkaluijl.supabase.co';
const KEY='sb_publishable_Ga0Ckx32Nckw5vvRYtZFHQ_AtzRI_2g';
const SESSION='teleprompter_cloud_session_v1';
const $=id=>document.getElementById(id);
let session=null,folders=[],scripts=[];
const headers=(extra={})=>({'apikey':KEY,'Authorization':`Bearer ${session?.access_token||KEY}`,'Content-Type':'application/json',...extra});
function saveSession(s){session=s;localStorage.setItem(SESSION,JSON.stringify(s))}
function clearSession(){session=null;localStorage.removeItem(SESSION)}
async function refresh(){if(!session?.refresh_token)return false;try{const r=await fetch(`${SUPA}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{'apikey':KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})});if(!r.ok)return false;saveSession(await r.json());return true}catch{return false}}
async function api(path,opt={}){let r=await fetch(SUPA+path,{...opt,headers:headers(opt.headers)});if(r.status===401&&await refresh())r=await fetch(SUPA+path,{...opt,headers:headers(opt.headers)});if(!r.ok)throw new Error((await r.text())||`HTTP ${r.status}`);if(r.status===204)return null;let t=await r.text();return t?JSON.parse(t):null}
function inject(){const lib=document.querySelector('.library');if(!lib||$('cloudBox'))return;const box=document.createElement('div');box.id='cloudBox';box.style.cssText='padding:12px;margin-bottom:12px;border:1px solid #3a3a3a;border-radius:14px;background:#171717';box.innerHTML=`<div style="font-weight:800;margin-bottom:8px">☁️ Sincronización de guiones</div><div id="cloudLoggedOut"><input id="cloudEmail" type="email" autocomplete="username" placeholder="Email" style="width:100%;height:44px;margin:4px 0;border:1px solid #444;border-radius:10px;background:#111;color:#fff;padding:0 10px"><input id="cloudPass" type="password" autocomplete="current-password" placeholder="Contraseña" style="width:100%;height:44px;margin:4px 0;border:1px solid #444;border-radius:10px;background:#111;color:#fff;padding:0 10px"><button id="cloudLogin" class="small gold" style="width:100%;margin-top:6px">Entrar y sincronizar</button></div><div id="cloudLoggedIn" hidden><div id="cloudUser" style="font-size:13px;color:#bbb;margin-bottom:8px"></div><button id="cloudSync" class="small gold">↻ Sincronizar</button> <button id="cloudLogout" class="small">Salir</button></div><div id="cloudStatus" style="font-size:12px;color:#aaa;margin-top:8px">Tus guiones quedan separados del ERP y protegidos por tu usuario.</div>`;lib.prepend(box);$('cloudLogin').onclick=login;$('cloudLogout').onclick=()=>{clearSession();setAuthUI(false);location.reload()};$('cloudSync').onclick=loadCloud;}
function setAuthUI(on){$('cloudLoggedOut').hidden=on;$('cloudLoggedIn').hidden=!on;if(on)$('cloudUser').textContent=`Conectado: ${session.user?.email||''}`}
async function login(){let email=$('cloudEmail').value.trim(),password=$('cloudPass').value;if(!email||!password)return status('Introduce email y contraseña.');status('Conectando…');try{let r=await fetch(`${SUPA}/auth/v1/token?grant_type=password`,{method:'POST',headers:{'apikey':KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});if(!r.ok)throw new Error('Usuario o contraseña incorrectos');saveSession(await r.json());setAuthUI(true);await loadCloud();await migrateLocal();}catch(e){status(e.message)}}
function status(t){if($('cloudStatus'))$('cloudStatus').textContent=t}
async function loadCloud(){try{status('Sincronizando…');folders=await api('/rest/v1/teleprompter_folders?select=id,name&order=created_at.asc')||[];scripts=await api('/rest/v1/teleprompter_scripts?select=id,folder_id,title,content,updated_at&order=updated_at.desc')||[];if(!folders.length){let f=await api('/rest/v1/teleprompter_folders',{method:'POST',headers:{'Prefer':'return=representation'},body:JSON.stringify({user_id:session.user.id,name:'General'})});folders=f||[];}bindCloud();renderCloud();status('✓ Guiones sincronizados en la nube.');}catch(e){status('Error al sincronizar: '+e.message)}}
function bindCloud(){const oldSave=$('saveScript'),oldNew=$('newFolder');if(oldSave&&!oldSave.dataset.cloud){let n=oldSave.cloneNode(true);n.dataset.cloud='1';oldSave.replaceWith(n);n.onclick=saveScript}if(oldNew&&!oldNew.dataset.cloud){let n=oldNew.cloneNode(true);n.dataset.cloud='1';oldNew.replaceWith(n);n.onclick=newFolder}$('folderSelect').onchange=renderCloud;}
function renderCloud(){let fs=$('folderSelect'),cur=fs.value;fs.innerHTML='';folders.forEach(f=>fs.add(new Option('☁️ '+f.name,f.id)));if(folders.some(f=>f.id===cur))fs.value=cur;let list=$('savedList');list.innerHTML='';let items=scripts.filter(s=>s.folder_id===fs.value);if(!items.length){list.innerHTML='<div class="emptyLib">No hay guiones en esta carpeta.</div>';return}items.forEach(s=>{let r=document.createElement('div');r.className='savedItem';let main=document.createElement('div');main.className='savedMain';let title=document.createElement('div');title.className='savedTitle';title.textContent=s.title;let meta=document.createElement('div');meta.className='savedMeta';meta.textContent='Guardado en la nube';main.append(title,meta);let o=document.createElement('button');o.textContent='Abrir';o.onclick=()=>{$('script').value=s.content;$('libraryText').value=s.content;$('scriptName').value=s.title;$('script').dispatchEvent(new Event('input'))};let d=document.createElement('button');d.textContent='Borrar';d.onclick=async()=>{if(!confirm('¿Borrar guion?'))return;await api(`/rest/v1/teleprompter_scripts?id=eq.${encodeURIComponent(s.id)}`,{method:'DELETE'});await loadCloud()};r.append(main,o,d);list.append(r)})}
async function newFolder(){let name=window.prompt('Nombre de la carpeta');if(!name?.trim())return;try{await api('/rest/v1/teleprompter_folders',{method:'POST',headers:{'Prefer':'return=minimal'},body:JSON.stringify({user_id:session.user.id,name:name.trim()})});await loadCloud()}catch(e){status('No se pudo crear la carpeta: '+e.message)}}
async function saveScript(){let title=$('scriptName').value.trim(),content=$('libraryText').value.trim(),folder_id=$('folderSelect').value;if(!title)return status('Pon un título al guion.');if(!content)return status('Escribe el contenido del guion.');try{let existing=scripts.find(s=>s.title===title&&s.folder_id===folder_id);if(existing)await api(`/rest/v1/teleprompter_scripts?id=eq.${encodeURIComponent(existing.id)}`,{method:'PATCH',headers:{'Prefer':'return=minimal'},body:JSON.stringify({title,content,folder_id})});else await api('/rest/v1/teleprompter_scripts',{method:'POST',headers:{'Prefer':'return=minimal'},body:JSON.stringify({user_id:session.user.id,folder_id,title,content})});$('script').value=content;$('script').dispatchEvent(new Event('input'));await loadCloud();status('✓ Guion guardado en la nube.');}catch(e){status('No se pudo guardar: '+e.message)}}
async function migrateLocal(){try{let raw=JSON.parse(localStorage.getItem('teleprompter_library_v1')||'null');if(!raw?.scripts?.length||localStorage.getItem('teleprompter_cloud_migrated'))return;let general=folders.find(f=>f.name==='General')||folders[0];for(const s of raw.scripts){if(!s.name||!s.text)continue;if(scripts.some(x=>x.title===s.name&&x.content===s.text))continue;await api('/rest/v1/teleprompter_scripts',{method:'POST',headers:{'Prefer':'return=minimal'},body:JSON.stringify({user_id:session.user.id,folder_id:general.id,title:s.name,content:s.text})})}localStorage.setItem('teleprompter_cloud_migrated','1');await loadCloud();status('✓ Guiones anteriores migrados a la nube.')}catch(e){status('Sincronizado; no se pudieron migrar algunos guiones locales.')}}
async function boot(){inject();try{session=JSON.parse(localStorage.getItem(SESSION)||'null')}catch{}if(session){if(!session.access_token&&!(await refresh())){clearSession();return}setAuthUI(true);await loadCloud();await migrateLocal()}else setAuthUI(false)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();